
--remove table if it exists
drop table if exists bookmarks;

--create the table
create table bookmarks (
  id INTEGER PRIMARY KEY generated by default as identity,
  title TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL UNIQUE,
  description TEXT,
  rating INTEGER NOT NULL DEFAULT 1,
  CHECK (rating > 0 AND rating < 6)
);

--insert table data
insert into bookmarks (title, url, description, rating)
  values
    ('crossfit', 'www.crossfit.com', 'High Intensity modality based training', 4),
    ('second', 'www.second.com', 'my description', 5),
    ('third', 'www.third.com', 'another description', 4),
    ('fourth', 'www.fourth.com', ' ', 2),
    ('fifth', 'www.fifth.com', 'pleading the fifth', 1),
    ('sixth', 'www.sixth.com', 'hello there', 3),
    ('seventh', 'www.seventh.com', 'try this one', 5),
    ('eigth', 'www.eigth.com', 'just need this to work', 5),
    ('ninth', 'www.ninth.com', 'not quite last', 4),
    ('tenth', 'www.tenth.com', 'last one', 2);
