CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY generated by default as identity,
  title TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL UNIQUE,
  description TEXT,
  rating INTEGER NOT NULL DEFAULT 1,
  CHECK (rating > 0 AND rating < 6)
);
